---
permalink: sm-storage/change-configuration-settings-for-a-volume-group.html 
sidebar: sidebar 
keywords: change, raid level, volume group 
summary: 您可以變更磁碟區群組的RAID層級、以符合存取磁碟區群組之應用程式的效能需求。此作業會變更磁碟區群組的RAID層級、而不會影響資料I/O 
---
= 變更磁碟區群組的RAID層級
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以變更磁碟區群組的RAID層級、以符合存取磁碟區群組之應用程式的效能需求。此作業可變更磁碟區群組的RAID層級、而不會影響資料I/O

.開始之前
* Volume群組必須處於最佳狀態。
* 您必須在Volume群組中擁有足夠的容量、才能轉換成新的RAID層級。
* 您無法變更集區的RAID層級。System Manager會自動將集區設定為RAID 6。


此作業開始後、您將無法取消。在此作業期間、您的資料仍可繼續使用。

深入瞭解RAID層級

[cols="2*"]
|===
| RAID層級 | 說明 


 a| 
RAID 0分段
 a| 
提供高效能、但不提供任何資料備援。如果磁碟區群組中的單一磁碟機故障、所有相關的磁碟區都會故障、而且所有資料都會遺失。

分段RAID群組將兩個或多個磁碟機合併成一個大型邏輯磁碟機。



 a| 
RAID 1鏡射
 a| 
提供高效能與最佳資料可用度、適合在公司或個人層級上儲存敏感資料。

自動將一個磁碟機的內容鏡射到鏡射配對中的第二個磁碟機、以保護您的資料。它可在單一磁碟機故障時提供保護。



 a| 
RAID 10分段/鏡射
 a| 
提供RAID 0（分段）和RAID 1（鏡射）的組合、並可在選取四個以上磁碟機時達成。

RAID 10適用於需要高效能和容錯能力的大量交易應用程式、例如資料庫。



 a| 
RAID 5
 a| 
最適合多使用者環境（例如資料庫或檔案系統儲存設備）、其中典型I/O大小較小、而且讀取活動比例較高。



 a| 
RAID 6
 a| 
最適合需要RAID 5以外的備援保護環境、但不需要高寫入效能。

|===
RAID 3只能使用命令列介面（CLI）指派給Volume群組。

.步驟
. 選取*功能表：Storage[資源池與磁碟區群組]*。
. 選取您要編輯的Volume群組、然後按一下*檢視/編輯設定*。
+
Volume Group設定對話方塊隨即出現。

. 從下拉式清單中選取RAID層級、然後按一下「*儲存*」。
+
如果容量減少、磁碟區備援遺失、或由於RAID層級變更而失去機櫃/藥櫃遺失保護、則會出現確認對話方塊。選擇* Yes*繼續；否則請按* No*。



當您變更Volume群組的RAID層級時、System Manager會變更組成Volume群組之每個Volume的RAID層級。在作業期間、效能可能會稍微受到影響。
