---
permalink: sm-mirroring/considerations-for-setting-up-asynchronous-mirroring.html 
sidebar: sidebar 
keywords: considerations, setting up, asynchronous, mirror 
summary: 為了確保組態設定成功、請在規劃過程中、謹記一些重要考量事項。 
---
= 設定非同步鏡射的考量
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
為了確保組態設定成功、請在規劃過程中、謹記一些重要考量事項。



== 啟動SANtricity NetApp統一化管理程式

* 主陣列和次陣列中的每個控制器都必須設定乙太網路管理連接埠、而且必須連線至您的網路。
* 非同步鏡射是透過開啟SANtricity 功能不整合管理程式來設定。任何鏡射關係都需要本機和遠端儲存系統被SANtricity 支援、並列於《支援統一化管理程式（NetApp Unified Manager）」中。
* 您必須SANtricity 安裝瀏覽器型的《統一化管理程式（WIR統一 化管理程式）」、並探索您想要在其中鏡射資料的兩個儲存陣列。接著、從Unified Manager中選取主磁碟區的儲存陣列、然後按一下「Launch」（啟動）以開啟瀏覽器型SANtricity 的《系統管理程式》。




== 正在啟動

在使用非同步鏡射之前、您必須在參與鏡射作業的每個儲存陣列上啟動它。您可以透過CLI、REST API或管理圖形化使用者介面（GUI）來啟動。

* 若為SANtricity 由NetApp系統管理程式（E2800、E5700、EF570）管理的系統、則不需要個別的啟動步驟；在設定鏡射群組/配對時、會在幕後執行啟動。
* 對於SANtricity 由E2700、E5600、EF560管理的系統、非同步鏡射會使用GUI啟動、而舊系統則不是SANtricity 由ESystem Manager管理。如果使用iSCSI進行非同步鏡射、則不需要執行啟動步驟。




== Web服務憑證和建議的瀏覽器

* *信任的憑證*
+
若鏡射涉及SANtricity 由NetApp System Manager管理的系統、建議您將信任的Web服務憑證匯入SANtricity 到NetApp Unified Manager中、以便儲存系統能與Web伺服器進行驗證。下列是使用NetApp統一化管理程式的步驟SANtricity ：

+
.. 針對SANtricity 安裝了NetApp Unified Manager的機器、產生憑證簽署要求（CSR）。
.. 將CSR傳送至憑證授權單位（CA）。
.. 當CA傳回簽署的憑證時、請在Unified Manager中匯入。


* *自我簽署的憑證*
+
也可以使用自我簽署的憑證。如果系統管理員嘗試設定鏡射而不匯入簽署的憑證、SANtricity 則會顯示錯誤對話方塊、讓系統管理員接受自我簽署的憑證。在此情況下、建議使用最新版本的Chrome或Firefox作為瀏覽器。

+
您可以接受自我簽署的憑證、或使用Unified Manager安裝自己的安全性憑證、並瀏覽至功能表：「Certificate [ Certificate Management（憑證管理）」。





== 支援的連線

非同步鏡射可以使用FC或iSCSI連線、或同時使用兩者來進行本機與遠端儲存系統之間的通訊。在建立鏡射一致性群組（也稱為非同步鏡射鏡射群組）時、如果兩個群組都連線至遠端儲存陣列、則系統管理員可以為該群組選取FC或iSCSI。沒有容錯移轉從一種通道類型移轉到另一種通道類型。

非同步鏡射會使用儲存陣列的主機端I/O連接埠、將鏡射資料從主端傳輸到次端。

* *透過光纖通道（FC）介面鏡射*
+
儲存陣列的每個控制器都會將其編號最高的FC主機連接埠專用於鏡射作業。

+
如果控制器同時具有基礎FC連接埠和主機介面卡（HIC）FC連接埠、則編號最高的連接埠位於HIC上。登入專用連接埠的任何主機都會登出、而且不會接受任何主機登入要求。此連接埠上的I/O要求僅接受參與鏡射作業的控制器。

+
專用鏡射連接埠必須連接至支援目錄服務和名稱服務介面的FC架構環境。特別是、參與鏡射關係的控制器之間、不支援使用FC-AL和點對點作為連線選項。

* *透過iSCSI介面鏡像*
+
與FC不同、iSCSI不需要專用連接埠。在iSCSI環境中使用非同步鏡射時、不需要將任何儲存陣列的前端iSCSI連接埠專用於非同步鏡射；這些連接埠會共用以進行非同步鏡射流量和主機對陣列I/O連線。

+
控制器會維護一份遠端儲存系統清單、iSCSI啟動器會嘗試建立工作階段。成功建立iSCSI連線的第一個連接埠、用於與該遠端儲存陣列進行所有後續通訊。如果通訊失敗、則會嘗試使用所有可用的連接埠來建立新的工作階段。

+
iSCSI連接埠是以連接埠為基礎、在陣列層級進行設定。組態訊息和資料傳輸的控制器間通訊使用全域設定、包括下列設定：

+
** VLAN：本機和遠端系統必須具有相同的VLAN設定才能進行通訊
** iSCSI接聽連接埠
** 巨型框架
** 乙太網路優先順序


+
[NOTE]
====
iSCSI互連控制器通訊必須使用主機連線連接埠、而非管理乙太網路連接埠。

====


非同步鏡射會使用儲存陣列的主機端I/O連接埠、將鏡射資料從主端傳輸到次端。因為非同步鏡射的目的是為了提供較高的延遲、較低成本的網路、所以iSCSI（因此以TCP/IP為基礎）連線非常適合它。在iSCSI環境中使用非同步鏡射時、不需要將陣列的任何前端iSCSI連接埠專用於非同步鏡射；這些連接埠可用於非同步鏡射流量和主機對陣列I/O連線
