---
permalink: sm-mirroring/create-synchronous-mirrored-volume.html 
sidebar: sidebar 
keywords: create, synchronous, mirrored, volume 
summary: 您可以同步鏡射磁碟區、以便在儲存陣列之間即時複寫資料、保護您的資訊、避免系統和站台故障。您可以選取要用於本機儲存陣列與遠端儲存陣列之間同步鏡射關係的主要磁碟區和次要磁碟區、以達成此目標。 
---
= 建立同步鏡射Volume
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以同步鏡射磁碟區、以便在儲存陣列之間即時複寫資料、保護您的資訊、避免系統和站台故障。您可以選取要用於本機儲存陣列與遠端儲存陣列之間同步鏡射關係的主要磁碟區和次要磁碟區、以達成此目標。

.開始之前
* 由於同步鏡射功能需要管理多個儲存陣列、因此SANtricity 您必須安裝瀏覽器型的《支援統一化管理程式》、並探索您要在其中鏡射資料的兩個儲存陣列。接著、從Unified Manager中選取主磁碟區的儲存陣列、然後按一下「Launch」（啟動）以開啟瀏覽器型SANtricity 的《系統管理程式》。
* 您必須有兩個儲存陣列。
* 每個儲存陣列都必須有兩個控制器。
* 主要和次要磁碟區的儲存陣列可執行不同的OS版本。支援的最低版本為7.84。
* 您必須知道本機和遠端儲存陣列的密碼。
* 您的本機和遠端儲存陣列必須透過光纖通道架構進行連線。
* 您必須同時建立要用於同步鏡射關係的主要和次要磁碟區。


同步鏡射磁碟區的程序有多個步驟：

*  1: Select the primary volume
*  2: Select the secondary volume
*  3: Select synchronization settings


一個Volume只能參與一個鏡射關係。



== 步驟1：選取主要Volume

[role="lead"]
您必須選取要用於同步鏡射關係的主要Volume。此磁碟區在鏡射關係中扮演主要角色。

.開始之前
* 您必須已建立要用於同步鏡射關係的主要Volume。
* 主Volume必須是標準Volume。它不能是精簡磁碟區或快照磁碟區。


.步驟
. 請執行下列其中一項動作、以存取同步鏡射順序：
+
** 選取功能表：Storage[同步鏡射>鏡射Volume ]。
** 選取功能表：「Storage[磁碟區>複製服務>同步鏡射磁碟區]。「*建立同步鏡射配對*」對話方塊隨即出現。


. 選取您要做為鏡射主要Volume的現有Volume。
+
[NOTE]
====
如果在「Volumes（磁碟區）」並排顯示中選取了一個磁碟區、且該磁碟區符合鏡射資格、則預設會選取該磁碟區。

====
. 選擇* Next*並前往  2: Select the secondary volume。




== 步驟2：選取次要Volume

[role="lead"]
您必須選取要用於鏡射關係的次要Volume。此Volume將在鏡射關係中擔任次要角色。

.開始之前
* 您必須已建立要用於同步鏡射關係的次要Volume。
* 次要Volume必須是標準Volume。它不能是精簡磁碟區或快照磁碟區。
* 次要Volume必須至少與主要Volume一樣大。


當您在遠端儲存陣列上選取次要磁碟區時、系統會顯示該鏡射配對的所有合格磁碟區清單。任何不符合使用資格的磁碟區都不會顯示在該清單中。

此對話方塊中顯示的磁碟區會依容量排序、從最接近主要磁碟區容量的磁碟區開始。容量相同的磁碟區會依字母順序排序。

.步驟
. 選取您要與本機儲存陣列建立鏡射關係的遠端儲存陣列。
+
[NOTE]
====
如果您的遠端儲存陣列受到密碼保護、系統會提示您輸入密碼。

====
+
** 儲存陣列會依其儲存陣列名稱列出。如果您尚未命名儲存陣列、則會將其列為「unnamed（未命名）」。
** 如果您要使用的儲存陣列不在清單中、請使用SANtricity 《企業管理》視窗（EMW）的《EWE Storage Manager》（英文）來新增。選取功能表：編輯[新增儲存陣列]。


. 選取您要在鏡射中作為次要Volume的現有Volume。
+
[NOTE]
====
如果選擇的次要Volume容量大於主要Volume、則可用容量僅限於主要Volume的大小。

====
. 單擊* Next*（下一步*）並轉至  3: Select synchronization settings。




== 步驟3：選取同步處理設定

[role="lead"]
您必須設定主要磁碟區的控制器擁有者在通訊中斷後、將資料與次要磁碟區重新同步的優先順序。您也必須選取手動或自動重新同步原則。

.步驟
. 使用滑桿列設定同步處理優先順序。
+
同步處理優先順序會決定在通訊中斷之後、與服務I/O要求相比、系統資源有多少用於完成初始同步處理和重新同步作業。

+
此對話方塊上設定的優先順序同時適用於主要Volume和次要Volume。您可以稍後選取功能表：Storage（同步鏡射）> More（更多）> Edit Settings]（編輯設定）、以修改主磁碟區的速率。

+
.更多關於同步速率的資訊
====
同步優先順序有五種：

** 最低
** 低
** 中
** 高
** 最高如果同步優先順序設定為最低速率、則會優先處理I/O活動、而且重新同步作業需要較長時間。如果同步優先順序設定為最高速率、則重新同步作業會優先處理、但儲存陣列的I/O活動可能會受到影響。


====
. 選擇是手動或自動重新同步遠端儲存陣列上的鏡射配對。
+
** *手動*（建議選項）-選取此選項、即可在將通訊還原至鏡射配對後、要求手動恢復同步。此選項提供最佳的資料恢復機會。
** *自動*-選取此選項可在將通訊還原至鏡射配對之後、自動開始重新同步。若要手動恢復同步、請前往功能表：Storage[同步鏡射]、反白顯示表格中的鏡射配對、然後在「More（更多）」下選取「恢復」。


. 按一下「*完成*」以完成同步鏡射順序。


System Manager會執行下列動作：

* 啟動同步鏡射功能。
* 開始在本機儲存陣列與遠端儲存陣列之間進行初始同步。
* 設定同步優先順序和重新同步原則。


選取功能表：首頁[檢視進行中的作業]以檢視同步鏡射作業的進度。這項作業可能會耗費大量時間、並可能影響系統效能。
