---
permalink: sm-hardware/configure-nvme-over-roce-ports-hardware.html 
sidebar: sidebar 
keywords: configure, nvme, roce, ports 
summary: 如果您的控制器包含NVMe over RoCE（透過整合式乙太網路的RDMA）連線、您可以從「Hardware（硬體）」頁面或「System（系統）」頁面設定NVMe連接埠設定。 
---
= 設定NVMe over RoCE連接埠
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您的控制器包含NVMe over RoCE（透過整合式乙太網路的RDMA）連線、您可以從「Hardware（硬體）」頁面或「System（系統）」頁面設定NVMe連接埠設定。

.開始之前
* 您的控制器必須包含NVMe over RoCE主機連接埠、否則系統管理員無法使用NVMe over RoCE設定。
* 您必須知道主機連線的IP位址。


您可以從「Hardware（硬體）」頁面或功能表：「Settings[System]（設定[系統]）」存取NVMe over RoCE組態。本工作說明如何從「*硬體*」頁面設定連接埠。

[NOTE]
====
NVMe over RoCE設定和功能只有在儲存陣列的控制器包含NVMe over RoCE連接埠時才會顯示。

====
.步驟
. 選取*硬體*。
. 如果圖形顯示磁碟機、請按一下*顯示磁碟櫃背面*。
+
圖形會變更、以顯示控制器而非磁碟機。

. 按一下要設定NVMe over RoCE連接埠的控制器。
+
此時會出現控制器的內容功能表。

. 選取*透過RoCE連接埠設定NVMe *。
+
「*設定NVMe over RoCE連接埠」對話方塊隨即開啟。

. 在下拉式清單中、選取您要設定的HIC連接埠。
. 單擊 * 下一步 * 。
+
若要查看所有連接埠設定、請按一下對話方塊右側的「Show More port settings（顯示更多連接埠設定）」連結。

+
.欄位詳細資料
====
|===
| 連接埠設定 | 說明 


 a| 
已設定乙太網路連接埠速度
 a| 
選取與連接埠上SFP速度功能相符的速度。



 a| 
啟用IPV4 /啟用IPv6
 a| 
選取一個或兩個選項、以啟用對IPv4和IPv6網路的支援。


NOTE: 如果您要停用連接埠存取、請取消選取這兩個核取方塊。



 a| 
MTU大小（按一下「Show More port settings（顯示更多連接埠設定）」即可取得。）
 a| 
如有必要、請為最大傳輸單元（MTU）輸入新的位元組大小。

預設的最大傳輸單元（MTU）大小為每個框架1500位元組。您必須輸入介於1500和9000之間的值。

|===
====
+
如果您選取「啟用IPV4」、則會在按「下一步」之後開啟一個對話方塊、供您選取「IPV4設定」。如果您選取「啟用IPv6」、則會在按「下一步」之後開啟一個對話方塊、供您選取IPv6設定。如果您同時選取這兩個選項、則會先開啟[IPV4設定]對話方塊、然後按一下[下一步]之後、隨即開啟IPv6設定對話方塊。

. 自動或手動設定IPv6和/或IPv6設定。
+
.欄位詳細資料
====
|===
| 連接埠設定 | 說明 


 a| 
自動取得組態
 a| 
選取此選項可自動取得組態。



 a| 
手動指定靜態組態
 a| 
選取此選項、然後在欄位中輸入靜態位址。（如有需要、您可以剪下地址並貼到欄位中。） 對於IPV4、請加入網路子網路遮罩和閘道。對於IPv6、請包含可路由的IP位址和路由器IP位址。

|===
====
. 單擊*完成*。

