---
permalink: sm-settings/step-1-complete-a-csr.html 
sidebar: sidebar 
keywords: complete, ca certificate, signing, request, csr, controllers 
summary: 若要接收儲存陣列控制器的憑證授權單位（CA）憑證、您必須先為儲存陣列中的每個控制器產生憑證簽署要求（CSR）檔案。 
---
= 完成控制器的CA憑證簽署要求（CSR）
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
若要接收儲存陣列控制器的憑證授權單位（CA）憑證、您必須先為儲存陣列中的每個控制器產生憑證簽署要求（CSR）檔案。

.開始之前
* 您必須以包含安全管理員權限的使用者設定檔登入。否則、不會顯示憑證功能。


.關於這項工作
此工作說明如何產生.CSR檔案（憑證簽署要求）、以便傳送給CA、以接收控制器的已簽署管理憑證。您必須提供組織的相關資訊、以及控制器的IP位址或DNS名稱。在此工作期間、如果儲存陣列中只有一個控制器、則會產生一個.csr檔案、如果有兩個控制器、則會產生兩個.csr檔案。

.步驟
. 選取功能表：設定[憑證]。
. 從* Array Management（陣列管理）*選項卡中選擇*完整的csr*。
+
[NOTE]
====
如果看到對話方塊提示您接受第二個控制器的自我簽署憑證、請按一下*「接受自我簽署的憑證*」繼續。

====
. 輸入下列資訊、然後按一下*下一步*：
+
** *組織*：貴公司或組織的完整法定名稱。包括尾碼、例如Inc.或Corp.
** *組織單位（選用）*：您組織處理憑證的部門。
** *城市/地區*：儲存陣列或企業所在的城市。
** *州/地區（選用）*：儲存陣列或業務所在的州或地區。
** *國家ISO代碼*：您所在國家/地區的兩位數ISO（國際標準化組織）代碼、例如US。


+
[CAUTION]
====
某些欄位可能會預先填入適當的資訊、例如控制器的IP位址。除非您確定預先填入的值不正確、否則請勿變更。例如、如果您尚未完成CSR、則控制器IP位址會設為「'localhost.」 在此情況下、您必須將「'localhost'」變更為控制器的DNS名稱或IP位址。

====
. 驗證或輸入儲存陣列中控制器A的下列資訊：
+
** *控制器一般名稱*-預設會顯示控制器A的IP位址或DNS名稱。請確定此位址正確無誤、而且必須完全符合您輸入的內容、才能在瀏覽器中存取System Manager。
** *控制器備用IP位址*-如果通用名稱是IP位址、您可以選擇輸入控制器A的任何其他IP位址或別名對於多個項目、請使用以逗號分隔的格式。
** *控制器A備用DNS名稱*-如果通用名稱是DNS名稱、請為控制器A輸入任何其他DNS名稱對於多個項目、請使用以逗號分隔的格式。如果沒有替代DNS名稱、但您在第一個欄位中輸入DNS名稱、請在此處複製該名稱。如果儲存陣列只有一個控制器、則可使用* Finish（完成）*按鈕。如果儲存陣列有兩個控制器、則可使用* Next*按鈕。


+
[NOTE]
====
當您初次建立CSR要求時、請勿按一下*跳過此步驟*連結。此連結是在錯誤恢復情況下提供的。在極少數情況下、CSR要求可能會在一個控制器上失敗、但在另一個控制器上失敗。此連結可讓您跳過在控制器A上建立CSR要求的步驟（如果已定義）、然後繼續下一步、在控制器B上重新建立CSR要求

====
. 如果只有一個控制器、請按一下「*完成*」。如果有兩個控制器、請按「*下一步*」輸入控制器B的資訊（與上述相同）、然後按一下「*完成*」。
+
對於單一控制器、會將一個.CSR檔案下載至您的本機系統。對於雙控制器、會下載兩個.CSR檔案。下載的資料夾位置取決於您的瀏覽器。

. 將.csr檔案傳送至CA。


.完成後
收到數位憑證時、請匯入CA傳送給您的適當憑證檔案。
